# Generated by Django 2.0.3 on 2018-05-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180512_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='zan',
            field=models.IntegerField(default=0),
        ),
    ]
