# Generated by Django 2.0.3 on 2018-05-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180513_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='picture',
            field=models.CharField(default='', max_length=500),
        ),
    ]
